services:
  # Article Service Definition
  articleservice:
    build:
      context: ./src
      dockerfile: ArticleService/Dockerfile
    ports:
      - "8001:80" # host port 8001, container bruger 80
    environment:
      - ASPNETCORE_URLS=http://+:80

  # Comment Service Definition
  commentservice:
    build:
      context: ./src
      dockerfile: CommentService/Dockerfile
    ports:
      - "8002:80" # host port 8002
    environment:
      - ASPNETCORE_URLS=http://+:80

  # Redis Service Definition
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    # command bruges s√• Redis configureres til at agere som LRU cache
    # memory med max 256MB
    command: redis-server --maxmemory 256mb --maxmemory-policy allkeys-lru

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    depends_on:
      - articleservice
      - commentservice

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
