version: '3.8'

services:
  # Article Service Definition
  articleservice:
    build:
      context: ./src
      dockerfile: ArticleService/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:80
    # This is the X-axis scaling command.
    deploy:
      replicas: 3

  commentservice:
    build:
      context: ./src
      dockerfile: CommentService/Dockerfile
    ports:
      - "8002:80"
    environment:
      - ASPNETCORE_URLS=http://+:80


  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    command: redis-server --maxmemory 256mb --maxmemory-policy allkeys-lru


  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    depends_on:
      - articleservice
      - commentservice


  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    depends_on:
      - prometheus

  # The Nginx Load Balancer Service
  loadbalancer:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8001:80"
    depends_on:
      - articleservice
